/* Mapping from Nominatim's class/type classificaton to German descriptive terms. 
   Based on the DE translation of the "search_osm_nominatim" section of the OSM website.
   Version 2016-02-03 including upstream fixes 2016-02-04
   For original see:
   https://github.com/openstreetmap/openstreetmap-website/blob/master/config/locales/de.yml
   and https://translatewiki.net/wiki/Translating:OpenStreetMap
*/
geocoder_searchtypes = {
    "aerialway": {
      "cable_car": "Kabelbahnwagen",
      "chair_lift": "Sessellift",
      "drag_lift": "Schlepplift",
      "gondola": "Gondelbahn",
      "station": "Gondelstation"
    },
    "aeroway": {
      "aerodrome": "Flugplatz",
      "apron": "Flugvorfeld",
      "gate": "Flugsteig",
      "helipad": "Hubschrauberlandeplatz",
      "runway": "Start- und Landebahn",
      "taxiway": "Rollbahn",
      "terminal": "Terminal"
    },
    "amenity": {
      "animal_shelter": "Tierheim",
      "arts_centre": "Kunstzentrum",
      "atm": "Geldautomat",
      "bank": "Bank",
      "bar": "Bar",
      "bbq": "Grillplatz",
      "bench": "Bank",
      "bicycle_parking": "Fahrrad-Stellplatz",
      "bicycle_rental": "Fahrradverleih",
      "biergarten": "Biergarten",
      "boat_rental": "Bootsverleih",
      "brothel": "Bordell",
      "bureau_de_change": "Wechselstube",
      "bus_station": "Busbahnhof",
      "cafe": "Café",
      "car_rental": "Autovermietung",
      "car_sharing": "Carsharing",
      "car_wash": "Autowaschanlage",
      "casino": "Casino",
      "charging_station": "Ladestation",
      "childcare": "Kinderbetreuung",
      "cinema": "Kino",
      "clinic": "Krankenhaus",
      "clock": "Uhr",
      "college": "Hochschule",
      "community_centre": "Gemeinschaftszentrum",
      "courthouse": "Gericht",
      "crematorium": "Krematorium",
      "dentist": "Zahnarzt",
      "doctors": "Arzt",
      "dormitory": "Studentenwohnheim",
      "drinking_water": "Trinkwasser",
      "driving_school": "Fahrschule",
      "embassy": "Botschaft",
      "emergency_phone": "Notrufsäule",
      "fast_food": "Schnellimbiss",
      "ferry_terminal": "Fähren-Anlaufstelle",
      "fire_hydrant": "Hydrant",
      "fire_station": "Feuerwehr",
      "food_court": "Food-Court",
      "fountain": "Springbrunnen",
      "fuel": "Tankstelle",
      "gambling": "Glücksspiel",
      "grave_yard": "Friedhof",
      "gym": "Fitnessstudio",
      "health_centre": "Gesundheitszentrum",
      "hospital": "Krankenhaus",
      "hunting_stand": "Hochstand",
      "ice_cream": "Eisdiele",
      "kindergarten": "Kindergarten",
      "library": "Bücherei",
      "market": "Markt",
      "marketplace": "Marktplatz",
      "monastery": "Kloster",
      "motorcycle_parking": "Motorradparkplatz",
      "nightclub": "Nachtklub",
      "nursery": "Kindertagesstätte",
      "nursing_home": "Altersheim",
      "office": "Büro",
      "parking": "Parkplatz",
      "parking_entrance": "Parkeinfahrt",
      "pharmacy": "Apotheke",
      "place_of_worship": "Andachtsstätte",
      "police": "Polizei",
      "post_box": "Briefkasten",
      "post_office": "Postamt",
      "preschool": "Vorschule",
      "prison": "Gefängnis",
      "pub": "Kneipe",
      "public_building": "Öffentliches Gebäude",
      "reception_area": "Empfangsbereich",
      "recycling": "Recycling-Center",
      "restaurant": "Restaurant",
      "retirement_home": "Altersheim",
      "sauna": "Sauna",
      "school": "Schule",
      "shelter": "Unterstand",
      "shop": "Geschäft",
      "shower": "Dusche",
      "social_centre": "Sozialzentrum",
      "social_club": "Social Club",
      "social_facility": "Soziale Einrichtung",
      "studio": "Studio",
      "swimming_pool": "Schwimmbecken",
      "taxi": "Taxi",
      "telephone": "Telefonzelle",
      "theatre": "Theater",
      "toilets": "WC",
      "townhall": "Rathaus",
      "university": "Universität",
      "vending_machine": "Selbstbedienungsautomat",
      "veterinary": "Tierarzt",
      "village_hall": "Gemeindezentrum",
      "waste_basket": "Mülleimer",
      "waste_disposal": "Abfallentsorgung",
      "youth_centre": "Jugendzentrum"
    },
    "boundary": {
      "administrative": "Verwaltungsgrenze",
      "census": "Grenze des Volkszählungsgebiets",
      "national_park": "Nationalpark",
      "protected_area": "Schutzgebiet"
    },
    "bridge": {
      "aqueduct": "Aquädukt",
      "suspension": "Hängebrücke",
      "swing": "Drehbrücke",
      "viaduct": "Viadukt",
      "yes": "Brücke"
    },
    "building": {
      "yes": "Gebäude"
    },
    "craft": {
      "brewery": "Brauerei",
      "carpenter": "Zimmermann",
      "electrician": "Elektriker",
      "gardener": "Gärtner",
      "painter": "Maler",
      "photographer": "Fotograf",
      "plumber": "Klempner",
      "shoemaker": "Schuhmacher",
      "tailor": "Schneider",
      "yes": "Handwerksgeschäft"
    },
    "emergency": {
      "ambulance_station": "Rettungswache",
      "defibrillator": "Defibrillator",
      "landing_site": "Notlandeplatz",
      "phone": "Notrufsäule"
    },
    "highway": {
      "abandoned": "Aufgegebene Straße",
      "bridleway": "Reitweg",
      "bus_guideway": "Busspur",
      "bus_stop": "Bushaltestelle",
      "construction": "Straße im Bau",
      "cycleway": "Radweg",
      "elevator": "Lift",
      "emergency_access_point": "Notrufpunkt",
      "footway": "Fußweg",
      "ford": "Furt",
      "living_street": "Spiel-/Wohnstraße",
      "milestone": "Kilometerstein",
      "motorway": "Autobahn",
      "motorway_junction": "Autobahnausfahrt/-kreuz",
      "motorway_link": "Autobahnauffahrt",
      "path": "Pfad (Wanderweg)",
      "pedestrian": "Fußgängerzone",
      "platform": "Bahnsteig",
      "primary": "Bundesstraße",
      "primary_link": "Bundesstraße-Auffahrt",
      "proposed": "Geplante Straße",
      "raceway": "Rennstrecke",
      "residential": "Wohnstraße",
      "rest_area": "Rastplatz",
      "road": "Straße",
      "secondary": "Landesstraße",
      "secondary_link": "Landesstraße-Auffahrt",
      "service": "Zufahrtsstraße",
      "services": "Autobahnraststätte",
      "speed_camera": "Blitzer",
      "steps": "Treppe",
      "street_lamp": "Straßenlaterne",
      "tertiary": "Hauptstraße",
      "tertiary_link": "Tertiärstraße-Auffahrt",
      "track": "Feldweg",
      "traffic_signals": "Lichtzeichenanlage",
      "trail": "Pfad",
      "trunk": "Schnellstraße",
      "trunk_link": "Schnellstraßenauffahrt",
      "unclassified": "Straße",
      "unsurfaced": "Nichtasphaltierte Straße",
      "yes": "Straße"
    },
    "historic": {
      "archaeological_site": "Ausgrabungsstätte",
      "battlefield": "Kampfgebiet",
      "boundary_stone": "Grenzstein",
      "building": "Historisches Gebäude",
      "bunker": "Bunker",
      "castle": "Schloss",
      "church": "Kirche",
      "city_gate": "Stadttor",
      "citywalls": "Stadtmauern",
      "fort": "Fort",
      "heritage": "Denkmalschutz",
      "house": "Historisches Haus",
      "icon": "Symbol",
      "manor": "Gutshaus",
      "memorial": "Denkmal",
      "mine": "Mine",
      "monument": "Monument",
      "roman_road": "Römerstraße",
      "ruins": "Ruine",
      "stone": "Findling",
      "tomb": "Grabstätte",
      "tower": "Historischer Turm",
      "wayside_cross": "Wegkreuz",
      "wayside_shrine": "Bildstock",
      "wreck": "Schiffswrack"
    },
    "junction": {
      "yes": "Kreuzung"
    },
    "landuse": {
      "allotments": "Kleingärten",
      "basin": "Becken",
      "brownfield": "Brachland",
      "cemetery": "Friedhof",
      "commercial": "Gewerbegebiet",
      "conservation": "Naturschutzgebiet",
      "construction": "Baustelle",
      "farm": "Bauernhof",
      "farmland": "Acker",
      "farmyard": "landwirtschaftliche Betriebsfläche",
      "forest": "Wald",
      "garages": "Garagen",
      "grass": "Wiese",
      "greenfield": "unerschlossenes Bauland",
      "industrial": "Industriegebiet",
      "landfill": "Deponie",
      "meadow": "Wiese",
      "military": "Militärgebiet",
      "mine": "Mine",
      "orchard": "Obstplantage",
      "quarry": "Steinbruch",
      "railway": "Bahngelände",
      "recreation_ground": "Erholungsgebiet",
      "reservoir": "Reservoir",
      "reservoir_watershed": "Wassereinzugsgebiet",
      "residential": "Siedlung",
      "retail": "Einzelhandel",
      "road": "Straßenfläche",
      "village_green": "Dorfwiese (brit.)",
      "vineyard": "Weinberg",
      "yes": "Bodennutzung"
    },
    "leisure": {
      "beach_resort": "Strandbad",
      "bird_hide": "Vogelbeobachtungshütte",
      "club": "Verein",
      "common": "öffentliche Grünfläche (brit.)",
      "dog_park": "Hundepark",
      "fishing": "Fischereigrund",
      "fitness_centre": "Fitnessstudio",
      "fitness_station": "Freiluft-Fitnesseinrichtung",
      "garden": "Garten",
      "golf_course": "Golfplatz",
      "horse_riding": "Reitanlage",
      "ice_rink": "Eislaufplatz",
      "marina": "Sporthafen",
      "miniature_golf": "Minigolf",
      "nature_reserve": "Naturschutzgebiet",
      "park": "Park",
      "pitch": "Sportplatz",
      "playground": "Spielplatz",
      "recreation_ground": "Erholungsgebiet",
      "resort": "Ferienort",
      "sauna": "Sauna",
      "slipway": "Slipanlage",
      "sports_centre": "Sportzentrum",
      "stadium": "Stadion",
      "swimming_pool": "Schwimmbecken",
      "track": "Laufbahn",
      "water_park": "Wasserpark",
      "yes": "Freizeit"
    },
    "man_made": {
      "lighthouse": "Leuchtturm",
      "pipeline": "Rohrleitung",
      "tower": "Turm",
      "works": "Fabrik",
      "yes": "menschgemacht"
    },
    "military": {
      "airfield": "Militärflugplatz",
      "barracks": "Kaserne",
      "bunker": "Bunker"
    },
    "mountain_pass": {
      "yes": "Gebirgspass"
    },
    "natural": {
      "bay": "Bucht",
      "beach": "Strand",
      "cape": "Kap",
      "cave_entrance": "Höhleneingang",
      "cliff": "Klippe",
      "crater": "Krater",
      "dune": "Düne",
      "fell": "Weide",
      "fjord": "Fjord",
      "forest": "Wald",
      "geyser": "Geysir",
      "glacier": "Gletscher",
      "grassland": "Wiese",
      "heath": "Heide",
      "hill": "Hügel",
      "island": "Insel",
      "land": "Land",
      "marsh": "Marsch",
      "moor": "Moor",
      "mud": "Schlick",
      "peak": "Gipfel",
      "point": "Punkt",
      "reef": "Riff",
      "ridge": "Grat",
      "rock": "Steine",
      "saddle": "Pass",
      "sand": "Sand",
      "scree": "Geröll",
      "scrub": "Buschland",
      "spring": "Quelle",
      "stone": "Findling",
      "strait": "Straße",
      "tree": "Baum",
      "valley": "Tal",
      "volcano": "Vulkan",
      "water": "Wasser",
      "wetland": "Feuchtgebiet",
      "wood": "Wald"
    },
    "office": {
      "accountant": "Buchhaltungsbüro",
      "administrative": "Verwaltung",
      "architect": "Architekt",
      "company": "Unternehmen",
      "employment_agency": "Arbeitsamt",
      "estate_agent": "Immobilienhändler",
      "government": "Amt",
      "insurance": "Krankenversicherungsbüro",
      "lawyer": "Rechtsanwalt",
      "ngo": "NGO",
      "telecommunication": "Telekommunikationsbüro",
      "travel_agent": "Reisebüro",
      "yes": "Büro"
    },
    "place": {
      "allotments": "Schrebergärten",
      "block": "Block",
      "airport": "Flughafen",
      "city": "Stadt",
      "country": "Staat",
      "county": "Bezirk",
      "farm": "Bauernhof",
      "hamlet": "Weiler",
      "house": "Haus",
      "houses": "Häuser",
      "island": "Insel",
      "islet": "Eiland",
      "isolated_dwelling": "Einzelgehöft",
      "locality": "Flur",
      "moor": "Moor",
      "municipality": "Gemeinde",
      "neighbourhood": "Wohngegend",
      "postcode": "Postleitzahl",
      "region": "Region",
      "sea": "Meer",
      "state": "Bundesland/-staat",
      "subdivision": "Vorort",
      "suburb": "Stadtteil",
      "town": "Stadt",
      "unincorporated_area": "Gemeindefreies Gebiet",
      "village": "Dorf",
      "yes": "Ort"
    },
    "railway": {
      "abandoned": "Aufgegebene Bahnstrecke",
      "construction": "Eisenbahn im Bau",
      "disused": "Aufgelassene Bahnstrecke",
      "disused_station": "Aufgelassener Bahnhof",
      "funicular": "Standseilbahn",
      "halt": "Haltepunkt",
      "historic_station": "Ehemaliger Bahnhof",
      "junction": "Bahnknoten",
      "level_crossing": "Eisenbahnkreuzung",
      "light_rail": "Stadtbahn",
      "miniature": "Miniaturbahn",
      "monorail": "Einschienenbahn",
      "narrow_gauge": "Schmalspurbahn",
      "platform": "Bahnsteig",
      "preserved": "Museumsbahn",
      "proposed": "Geplante Bahnstrecke",
      "spur": "Anschlussgleis",
      "station": "Bahnhof",
      "stop": "Haltepunkt",
      "subway": "U-Bahn",
      "subway_entrance": "U-Bahn-Eingang",
      "switch": "Weiche",
      "tram": "Straßenbahn",
      "tram_stop": "Haltestelle"
    },
    "shop": {
      "alcohol": "Spirituosenladen",
      "antiques": "Antiquitätengeschäft",
      "art": "Kunstladen",
      "bakery": "Bäckerei",
      "beauty": "Parfümerie",
      "beverages": "Getränkemarkt",
      "bicycle": "Fahrradgeschäft",
      "books": "Buchgeschäft",
      "boutique": "Boutique",
      "butcher": "Metzgerei",
      "car": "Autohaus",
      "car_parts": "Autoteilehändler",
      "car_repair": "Autowerkstatt",
      "carpet": "Teppichladen",
      "charity": "Wohltätigkeitsladen",
      "chemist": "Drogerie",
      "clothes": "Bekleidungsgeschäft",
      "computer": "Computergeschäft",
      "confectionery": "Konditorei",
      "convenience": "Tante-Emma-Laden",
      "copyshop": "Copyshop",
      "cosmetics": "Parfümerie",
      "deli": "Feinkostladen",
      "department_store": "Kaufhaus",
      "discount": "Diskontladen",
      "doityourself": "Baumarkt",
      "dry_cleaning": "Textilreinigung",
      "electronics": "Elektronikgeschäft",
      "estate_agent": "Immobilienhändler",
      "farm": "Hofladen",
      "fashion": "Modegeschäft",
      "fish": "Fischereiladen",
      "florist": "Blumengeschäft",
      "food": "Lebensmittelladen",
      "funeral_directors": "Bestattungsunternehmen",
      "furniture": "Möbelgeschäft",
      "gallery": "Galerie",
      "garden_centre": "Gartenzentrum",
      "general": "Gemischtwarenladen",
      "gift": "Geschenkeladen",
      "greengrocer": "Obst- und Gemüsehändler",
      "grocery": "Lebensmittelladen",
      "hairdresser": "Frisör",
      "hardware": "Eisenwarenhändler",
      "hifi": "Elektroshop",
      "insurance": "Versicherungsbüro",
      "jewelry": "Juwelier",
      "kiosk": "Kiosk",
      "laundry": "Wäscherei",
      "mall": "Einkaufszentrum",
      "market": "Markt",
      "mobile_phone": "Handygeschäft",
      "motorcycle": "Motorradgeschäft",
      "music": "Musikladen",
      "newsagent": "Zeitungsladen",
      "optician": "Optiker",
      "organic": "Bio-Laden",
      "outdoor": "Outdoor-Ausrüster",
      "pet": "Tierhandlung",
      "pharmacy": "Apotheke",
      "photo": "Fotoladen",
      "salon": "Salon",
      "second_hand": "Second-Hand-Geschäft",
      "shoes": "Schuhgeschäft",
      "shopping_centre": "Einkaufszentrum",
      "sports": "Sportgeschäft",
      "stationery": "Schreibwarenladen",
      "supermarket": "Supermarkt",
      "tailor": "Schneiderei",
      "toys": "Spielwarengeschäft",
      "travel_agency": "Reisebüro",
      "video": "Videothek",
      "wine": "Vinothek",
      "yes": "Geschäft"
    },
    "tourism": {
      "alpine_hut": "Berghütte",
      "apartment": "Ferienwohnung",
      "artwork": "Kunstwerk",
      "attraction": "Sehenswürdigkeit",
      "bed_and_breakfast": "Bed and Breakfast",
      "cabin": "Hütte",
      "camp_site": "Campingplatz",
      "caravan_site": "Wohnmobile-Stellplatz",
      "chalet": "Chalet",
      "gallery": "Galerie",
      "guest_house": "Pension",
      "hostel": "Jugendherberge",
      "hotel": "Hotel",
      "information": "Information",
      "motel": "Motel",
      "museum": "Museum",
      "picnic_site": "Piknikplatz",
      "theme_park": "Freizeitpark",
      "viewpoint": "Aussichtspunkt",
      "zoo": "Zoo"
    },
    "tunnel": {
      "culvert": "Durchlass",
      "yes": "Tunnel"
    },
    "waterway": {
      "artificial": "Künstliche Wasserstraße",
      "boatyard": "Werft",
      "canal": "Kanal",
      "dam": "Staudamm",
      "derelict_canal": "Aufgelassener Kanal",
      "ditch": "Wassergraben",
      "dock": "Dock",
      "drain": "Abwassergraben",
      "lock": "Schleuse",
      "lock_gate": "Schleusentor",
      "mooring": "Anlegeplatz",
      "rapids": "Stromschnellen",
      "river": "Fluss",
      "stream": "Bach",
      "wadi": "Trockental",
      "waterfall": "Wasserfall",
      "weir": "Wehr",
      "yes": "Wasserstraße"
    }
  }
